### ISSUE TITLE
Do we need SafeAreaView?

### ISSUE THREAD

**Issue by fede-rodes** [SportySpots/cruijff#171]
Take a look at: https://v1.reactnavigation.org/docs/handling-iphonex.html

Then, we should probably do something here (?):
https://github.com/SportySpots/cruijff/blob/master/App/Navigation/AppNavigation.js#L38
https://github.com/SportySpots/cruijff/blob/master/App/Navigation/AppNavigation.js#L66

I'm no 100% sure!

**Comment by Tommos0** [comment]
has been done!
